INSERT INTO words(id, lemma, part_of_speech, transcription, meaning, level, created_at)
VALUES (31, 'example', 'noun', 'ɪɡˈzɑːmpl',
        'a thing characteristic of its kind', 'A1', now()),
       (32, 'accommodation', 'noun', 'əˌkɒməˈdeɪʃən',
        'a place to live or stay', 'A1', now()),
       (33, 'restaurant', 'noun', 'ˈrestərɒnt',
        'a place where meals are prepared and served', 'A1', now()),
       (34, 'environment', 'noun', 'ɪnˈvaɪərənmənt',
        'the surroundings in which something exists', 'A1', now()),
       (35, 'beautiful', 'adjective', 'ˈbjuːtɪfəl',
        'pleasing to the senses or mind', 'A1', now()),
       (36, 'necessary', 'adjective', 'ˈnesəseri',
        'needed or required', 'A1', now()),
       (37, 'separate', 'adjective', 'ˈsepərət',
        'existing or happening independently', 'A1', now());